# Generated by Django 5.0.4 on 2024-05-06 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Patient_id', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Study_Id', models.CharField()),
                ('Instances_Id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('Date_Study', models.DateField()),
                ('CEM', models.BooleanField()),
                ('Classification', models.BooleanField()),
                ('right_breast', models.BooleanField()),
                ('left_breast', models.BooleanField()),
            ],
        ),
    ]
