# Generated by Django 5.0.4 on 2024-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examlist', '0002_remove_examlist_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlist',
            name='Classification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
