# Generated by Django 5.0.6 on 2024-06-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examlist', '0003_examlist_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='instance_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laterality', models.CharField()),
                ('Type', models.CharField()),
                ('view', models.CharField()),
                ('instance_id', models.CharField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_id', to='examlist.examlist')),
            ],
        ),
    ]
