# Generated by Django 5.0.4 on 2024-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examlist', '0004_instance_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlist',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
